# State machine configuration for Micro Fluidic System
name: "Micro Fluidic System"
initial_state: "initialize"
settings:
  ignore_invalid_triggers: true
  auto_transitions: false
  port: 8083

states:
  - name: "initialize"
    transitions:
        trigger: "initialize_finished"
        dest: "before_cycle_stage_1"
    actions:
      - initialize
    

  # Before cycle stages
  - name: "before_cycle_stage_1"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_2"
    actions:
      - tray_to_pump: (0, 0)

  - name: "before_cycle_stage_2"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_3"
    actions:
      - rotate_table_p

  - name: "before_cycle_stage_3"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_4"
    actions:
      - fill_bottle: ("test_input")
      - tray_to_pump: (0, 0)

  - name: "before_cycle_stage_4"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_5"
    actions:
      - rotate_table_p

  - name: "before_cycle_stage_5"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_6"
    actions:
      - fill_bottle: ("test_input")
      - pump_to_measure: (0, 0)

  - name: "before_cycle_stage_6"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_7"
    actions:
      - rotate_table_m

  - name: "before_cycle_stage_7"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_8"
    actions:
      - tray_to_pump: (0, 0)
      - measure_UV

  - name: "before_cycle_stage_8"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_9"
    actions:
      - rotate_table_p

  - name: "before_cycle_stage_9"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_10"
    actions:
      - fill_bottle: ("test_input")
      - pump_to_measure: (0, 0)

  - name: "before_cycle_stage_10"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_11"
    actions:
      - rotate_table_m

  - name: "before_cycle_stage_11"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_12"
    actions:
      - tray_to_pump: (0, 0)

  - name: "before_cycle_stage_12"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_13"
    actions:
      - rotate_table_p

  - name: "before_cycle_stage_13"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_14"
    actions:
      - fill_bottle: ("test_input")
      - pump_to_measure: (0, 0)
      - measure_DLS
      - measure_UV

  - name: "before_cycle_stage_14"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_15"
    actions:
      - rotate_table_m

  - name: "before_cycle_stage_15"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_16"
    actions:
      - tray_to_pump: (0, 0)

  - name: "before_cycle_stage_16"
    transitions:
        trigger: "command_finished"
        dest: "before_cycle_stage_17"
    actions:
      - rotate_table_p

  - name: "before_cycle_stage_17"
    transitions:
        trigger: "command_finished"
        dest: "cycle_stage_1"
    actions:
      - fill_bottle: ("test_input")
      - measure_DLS
      - measure_UV

  # Cycle stages
  - name: "cycle_stage_1"
    transitions:
        trigger: "command_finished"
        dest: "cycle_stage_2"
    actions:
      - measure_to_tray: (0, 0)

  - name: "cycle_stage_2"
    transitions:
        trigger: "command_finished"
        dest: "cycle_stage_3"
    actions:
      - pump_to_measure: (0, 0)

  - name: "cycle_stage_3"
    transitions:
        trigger: "command_finished"
        dest: "cycle_stage_4"
    actions:
      - rotate_table_m

  - name: "cycle_stage_4"
    transitions:
        trigger: "command_finished"
        dest: "cycle_stage_branch"
        conditions: "is_bottle_on_tray"
    actions:
      - measure_DLS
      - measure_UV

  - name: "cycle_stage_branch"
    transitions:
        trigger: "command_finished"
        dest: "cycle_stage_6"
    actions:
      - tray_to_pump: (0, 0)

  - name: "cycle_stage_6"
    transitions:
        trigger: "command_finished"
        dest: "cycle_stage_7"
    actions:
      - rotate_table_p

  - name: "cycle_stage_7"
    transitions:
        trigger: "command_finished"
        dest: "cycle_stage_1"
    actions:
      - fill_bottle: ("test_input")
  
  - name: "cycle_stage_4"
    transitions:
        trigger: "command_finished"
        dest: "after_cycle_stage"
        unless: "is_bottle_on_tray"
    actions:
      - measure_DLS
      - measure_UV

  # After cycle stages
  - name: "after_cycle_stage"
    transitions:
        trigger: "command_finished"
        dest: "after_cycle_stage_2"
    actions:
      - rotate_table_p

  - name: "after_cycle_stage_2"
    transitions:
        trigger: "command_finished"
        dest: "after_cycle_stage_3"
    actions:
      - measure_to_tray: (0, 0)

  - name: "after_cycle_stage_3"
    transitions:
        trigger: "command_finished"
        dest: "after_cycle_stage_4"
    actions:
      - pump_to_measure: (0, 0)

  - name: "after_cycle_stage_4"
    transitions:
        trigger: "command_finished"
        dest: "after_cycle_stage_5"
    actions:
      - rotate_table_m

  - name: "after_cycle_stage_5"
    transitions:
        trigger: "command_finished"
        dest: "after_cycle_stage_6"
    actions:
      - measure_DLS
      - measure_UV
      - measure_to_tray: (0, 0)

  - name: "after_cycle_stage_6"
    transitions:
        trigger: "command_finished"
        dest: "after_cycle_stage_7"
    actions:
      - rotate_table_m

  - name: "after_cycle_stage_7"
    transitions:
        trigger: "command_finished"
        dest: "after_cycle_stage_8"
    actions:
      - measure_DLS
      - measure_to_tray: (0, 0)

  - name: "after_cycle_stage_8"
    transitions:
        trigger: "command_finished"
        dest: "after_cycle_stage_9"
    actions:
      - rotate_table_m
  
  - name: "after_cycle_stage_9"
    transitions:
        trigger: "command_finished"
        dest: "end"
    actions:
      - measure_to_tray: (0, 0)
    
  - name: "end"
    


