# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QRectF


class ClickableRectangle(QtWidgets.QGraphicsRectItem):
    def __init__(self, rect, color, parent=None):
        super().__init__(rect, parent)
        self.default_color = color
        self.setBrush(QtGui.QBrush(self.default_color))
        self.setFlags(
            QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIsSelectable
            | QtWidgets.QGraphicsItem.GraphicsItemFlag.ItemIsMovable
        )

    def mousePressEvent(self, event):
        """Handle mouse press event."""
        # Change color on click
        self.setBrush(QtGui.QBrush(QtGui.QColor("yellow")))
        print("Rectangle clicked!")
        super().mousePressEvent(event)

    def mouseReleaseEvent(self, event):
        """Handle mouse release event."""
        # Restore original color
        self.setBrush(QtGui.QBrush(self.default_color))
        super().mouseReleaseEvent(event)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.graphicsView_pumps = QtWidgets.QGraphicsView(parent=self.groupBox)
        self.graphicsView_pumps.setGeometry(QtCore.QRect(60, 20, 256, 192))
        self.graphicsView_pumps.setObjectName("graphicsView_pumps")

        # Create a QGraphicsScene
        self.scene = QtWidgets.QGraphicsScene()
        self.graphicsView_pumps.setScene(self.scene)

        # Set the scene dimensions
        self.scene.setSceneRect(0, 0, 100, 100)

        # Add a clickable rectangle to the scene
        self.rect_item1 = ClickableRectangle(
            QRectF(10, 10, 20, 50), QtGui.QColor("lightblue")
        )
        self.rect_item2 = ClickableRectangle(
            QRectF(40, 10, 20, 50), QtGui.QColor("lightblue")
        )
        self.scene.addItem(self.rect_item1)
        self.scene.addItem(self.rect_item2)

        self.lineEdit_name_sol = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEdit_name_sol.setGeometry(QtCore.QRect(60, 240, 113, 20))
        self.lineEdit_name_sol.setObjectName("lineEdit_name_sol")
        self.spinBox_volume = QtWidgets.QSpinBox(parent=self.groupBox)
        self.spinBox_volume.setGeometry(QtCore.QRect(60, 280, 71, 22))
        self.spinBox_volume.setObjectName("spinBox_volume")
        self.spinBox_concentration = QtWidgets.QSpinBox(parent=self.groupBox)
        self.spinBox_concentration.setGeometry(QtCore.QRect(60, 320, 71, 22))
        self.spinBox_concentration.setObjectName("spinBox_concentration")
        self.pushButton_pump_set = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButton_pump_set.setGeometry(QtCore.QRect(150, 350, 75, 23))
        self.pushButton_pump_set.setObjectName("pushButton_pump_set")
        self.progressBar_pump = QtWidgets.QProgressBar(parent=self.groupBox)
        self.progressBar_pump.setGeometry(QtCore.QRect(140, 390, 118, 23))
        self.progressBar_pump.setProperty("value", 24)
        self.progressBar_pump.setObjectName("progressBar_pump")
        self.groupBox_measure_setup = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_measure_setup.setGeometry(QtCore.QRect(220, 430, 120, 80))
        self.groupBox_measure_setup.setObjectName("groupBox_measure_setup")
        self.groupBox_filling_measure_select = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_filling_measure_select.setGeometry(QtCore.QRect(50, 430, 120, 80))
        self.groupBox_filling_measure_select.setObjectName(
            "groupBox_filling_measure_select"
        )
        self.widget = QtWidgets.QWidget(parent=self.groupBox_filling_measure_select)
        self.widget.setGeometry(QtCore.QRect(10, 20, 91, 51))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_filling = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_filling.setObjectName("checkBox_filling")
        self.verticalLayout.addWidget(self.checkBox_filling)
        self.checkBox_measure = QtWidgets.QCheckBox(parent=self.widget)
        self.checkBox_measure.setObjectName("checkBox_measure")
        self.verticalLayout.addWidget(self.checkBox_measure)
        self.widget1 = QtWidgets.QWidget(parent=self.groupBox)
        self.widget1.setGeometry(QtCore.QRect(90, 170, 172, 19))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_p1 = QtWidgets.QRadioButton(parent=self.widget1)
        self.radioButton_p1.setObjectName("radioButton_p1")
        self.horizontalLayout.addWidget(self.radioButton_p1)
        self.radioButton_p2 = QtWidgets.QRadioButton(parent=self.widget1)
        self.radioButton_p2.setObjectName("radioButton_p2")
        self.horizontalLayout.addWidget(self.radioButton_p2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsView_samples = QtWidgets.QGraphicsView(parent=self.groupBox_2)
        self.graphicsView_samples.setGeometry(QtCore.QRect(70, 60, 256, 192))
        self.graphicsView_samples.setObjectName("graphicsView_samples")
        self.pushButton_bottle1 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_bottle1.setGeometry(QtCore.QRect(110, 110, 75, 23))
        self.pushButton_bottle1.setObjectName("pushButton_bottle1")
        self.pushButton_bottle2 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_bottle2.setGeometry(QtCore.QRect(210, 110, 75, 23))
        self.pushButton_bottle2.setObjectName("pushButton_bottle2")
        self.pushButton_bottle3 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_bottle3.setGeometry(QtCore.QRect(110, 150, 75, 23))
        self.pushButton_bottle3.setObjectName("pushButton_bottle3")
        self.pushButton_bottle4 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_bottle4.setGeometry(QtCore.QRect(210, 150, 75, 23))
        self.pushButton_bottle4.setObjectName("pushButton_bottle4")
        self.lineEdit_sample_vol = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_sample_vol.setGeometry(QtCore.QRect(70, 280, 113, 20))
        self.lineEdit_sample_vol.setObjectName("lineEdit_sample_vol")
        self.lineEdit_ratio_nano = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEdit_ratio_nano.setGeometry(QtCore.QRect(70, 330, 113, 20))
        self.lineEdit_ratio_nano.setObjectName("lineEdit_ratio_nano")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 300, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_sol_setup = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_sol_setup.setGeometry(QtCore.QRect(30, 380, 211, 51))
        self.groupBox_sol_setup.setObjectName("groupBox_sol_setup")
        self.groupBox_non_sol_setup = QtWidgets.QGroupBox(parent=self.groupBox_2)
        self.groupBox_non_sol_setup.setGeometry(QtCore.QRect(30, 440, 211, 51))
        self.groupBox_non_sol_setup.setObjectName("groupBox_non_sol_setup")
        self.radioButton_with_light = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_with_light.setGeometry(QtCore.QRect(290, 420, 82, 17))
        self.radioButton_with_light.setObjectName("radioButton_with_light")
        self.pushButton_start = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.pushButton_start.setGeometry(QtCore.QRect(40, 500, 75, 23))
        self.pushButton_start.setObjectName("pushButton_start")
        self.progressBar_sample = QtWidgets.QProgressBar(parent=self.groupBox_2)
        self.progressBar_sample.setGeometry(QtCore.QRect(150, 500, 118, 23))
        self.progressBar_sample.setProperty("value", 24)
        self.progressBar_sample.setObjectName("progressBar_sample")
        self.widget2 = QtWidgets.QWidget(parent=self.groupBox_2)
        self.widget2.setGeometry(QtCore.QRect(130, 30, 129, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox_num_samples = QtWidgets.QSpinBox(parent=self.widget2)
        self.spinBox_num_samples.setObjectName("spinBox_num_samples")
        self.horizontalLayout_2.addWidget(self.spinBox_num_samples)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Step 1: Pump Setup"))
        self.pushButton_pump_set.setText(_translate("MainWindow", "PushButton"))
        self.groupBox_measure_setup.setTitle(_translate("MainWindow", "GroupBox"))
        self.groupBox_filling_measure_select.setTitle(
            _translate("MainWindow", "GroupBox")
        )
        self.checkBox_filling.setText(_translate("MainWindow", "Filling "))
        self.checkBox_measure.setText(_translate("MainWindow", "Measuring"))
        self.radioButton_p1.setText(_translate("MainWindow", "RadioButton"))
        self.radioButton_p2.setText(_translate("MainWindow", "RadioButton"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Step 2: Sample Setup"))
        self.pushButton_bottle1.setText(_translate("MainWindow", "Bottle0_0"))
        self.pushButton_bottle2.setText(_translate("MainWindow", "Bottle0_1"))
        self.pushButton_bottle3.setText(_translate("MainWindow", "Bottle1_0"))
        self.pushButton_bottle4.setText(_translate("MainWindow", "Bottle1_1"))
        self.pushButton_6.setText(_translate("MainWindow", "Apply for All"))
        self.groupBox_sol_setup.setTitle(_translate("MainWindow", "Solvent Setup"))
        self.groupBox_non_sol_setup.setTitle(
            _translate("MainWindow", "Non-Solvent Setup")
        )
        self.radioButton_with_light.setText(_translate("MainWindow", "With Light"))
        self.pushButton_start.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "Num. of Samples:"))
